apiVersion: v1
kind: Service
metadata:
  name: svc-udm
  labels:
    app: svc-udm
  namespace: 5gc-udm
spec:
  #type: ClusterIP
  #clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    name: http2
    #protocol: TCP
    #  - port: 443
    #    targetPort: 443
    #    name: https
    #protocol: TCP
  selector:
    app: udm

